"""add challenge tries count and refusing

Revision ID: 737cce098026
Revises: 83d26b5634e0
Create Date: 2026-01-10 10:55:53.244082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737cce098026'
down_revision: Union[str, Sequence[str], None] = '83d26b5634e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'challenges',
        sa.Column('tries', sa.Integer(), nullable=True)
    )

    op.execute("UPDATE challenges SET tries = 0")

    op.alter_column(
        'challenges',
        'tries',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'tries')
    # ### end Alembic commands ###
