"""ip_pool quarantine_until

Revision ID: aa919f815781
Revises: f82595280013
Create Date: 2026-01-03 23:31:06.817212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa919f815781'
down_revision: Union[str, Sequence[str], None] = 'f82595280013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_pool', sa.Column('quarantined_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_ip_pool_quarantined_until'), 'ip_pool', ['quarantined_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_pool_quarantined_until'), table_name='ip_pool')
    op.drop_column('ip_pool', 'quarantined_until')
    # ### end Alembic commands ###
